title: JLib Inspector
description: Runtime inventory of the libraries actually loaded by your JVM.
url: https://brunoborges.github.io
baseurl: /jlib-inspector
repository: brunoborges/jlib-inspector
theme: minima
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile*
  - vendor

defaults:
  - scope:
      path: "javadoc"
    values:
      layout: null
      sitemap: false
      render_with_liquid: false

nav:
  - text: Home
    url: /
  - text: Why
    url: /#why
  - text: Architecture
    url: /#architecture
  - text: Quick Start
    url: /#quick-start
  - text: GitHub
    url: https://github.com/brunoborges/jlib-inspector
  - text: Javadoc
    url: /javadoc/

# Social / SEO extras (optional placeholders)
twitter_username: brunoborges
github_username:  brunoborges
logo: /assets/img/logo.svg

