# .github/workflows/release.yml
name: release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Temurin JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build
        run: mvn -B -DskipTests=false verify

      - name: Collect artifacts
        run: |
          mkdir -p artifacts
          ls -l agent/target || true
          ls -l server/target || true
          cp agent/target/*shaded.jar artifacts/ || echo "No agent shaded jar found" >&2
          cp server/target/*shaded.jar artifacts/ || echo "No server shaded jar found" >&2
          ls -l artifacts


      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shaded-jars
          path: artifacts/*.jar
          if-no-files-found: error

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write  # needed to create the release
    steps:
      - name: Determine tag
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ inputs.manual_tag }}" ]]; then
            echo "tag=${{ inputs.manual_tag }}" >> "$GITHUB_OUTPUT"
          else
            # refs/tags/v1.2.3 -> v1.2.3
            echo "tag=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
          fi
          echo "Resolved tag: $(grep tag= $GITHUB_OUTPUT)"

      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: shaded-jars
          path: artifacts

      - name: Generate checksums
        run: |
          cd artifacts
          for f in *.jar; do
            sha256sum "$f" > "$f.sha256"
          done
          ls -1

      - name: Generate release notes (simple)
        id: notes
        run: |
          {
            echo "notes<<'EOF'"
            echo "# Release ${{ steps.vars.outputs.tag }}"
            echo
            echo "Artifacts:"
            for f in artifacts/*.jar; do
              bn=$(basename "$f")
              echo "- $bn"
            done
            echo
            echo "Checksums (SHA256):"
            echo '````'
            for f in artifacts/*.sha256; do
              cat "$f"
            done
            echo '````'
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          name: Release ${{ steps.vars.outputs.tag }}
          body: ${{ steps.notes.outputs.notes }}
          draft: false
          prerelease: false
          files: |
            artifacts/*.jar
            artifacts/*.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          echo "## Published Release" >> $GITHUB_STEP_SUMMARY
          echo "Tag: ${{ steps.vars.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
          echo "Artifacts:" >> $GITHUB_STEP_SUMMARY
          ls -1 artifacts/*.jar >> $GITHUB_STEP_SUMMARY