name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

env:
  JAVA_VERSION: '21'
  NODE_VERSION: '18'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh || true

      - name: Get version
        id: version
        env:
          INPUT_VERSION: ${{ github.event.inputs.version }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: .github/scripts/get-version.sh

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Java
        run: .github/scripts/build-java.sh

      - name: Build frontend
        run: .github/scripts/build-frontend.sh

      - name: Create release package
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: .github/scripts/create-release-package.sh

      - name: Generate changelog
        id: changelog
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: .github/scripts/generate-changelog.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: JLib Inspector ${{ steps.version.outputs.VERSION }}
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: ${{ contains(steps.version.outputs.VERSION, '-') }}
          files: |
            jlib-inspector-${{ steps.version.outputs.VERSION }}.tar.gz
            jlib-inspector-${{ steps.version.outputs.VERSION }}-linux.tar.gz
            jlib-inspector-${{ steps.version.outputs.VERSION }}-windows.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
